### PR TITLE
refactor: use zuehlke reveal package via cdn

### LINKED ISSUE #2: [Styling]: Refactor to zuehlke-reveal-package
Use the https://github.com/webplatformz/zuehlke-reveal-package the same way the css-course does: https://github.com/webplatformz/css-course

### PR DESCRIPTION
**Pull request by meck93**
closes #2 

## State

It works! (For almost all pages out of the box). 

## To Do 

- [x] figure out why one slide doesn't look as expected (code not highlighted) -> Chapter 06 Hooks -> Slide 02/02 contains the following code
```
    // define a name state with the initial value of ""
    const [name, setName] = useState("");

    // The variable contains the current state value
    <p>Name: {name}</p>
```

### CODE REVIEW

**Comment by felixmokross** [comment]
Nice, thank you!

The index.html shows the serif font for me though, although it should be sans-serif even according to the computed CSS.. We should look into that.

And if one of us gets to it, I think we should also replace the background picture of index.html to adapt to the new look. What do you think should we do it in this PR or merge this now and have a look later? Other than that it looks good to me.

image

**Review by felixmokross — COMMENTED** [review]
Nice, thank you!

The index.html shows the serif font for me though, although it should be sans-serif even according to the computed CSS.. We should look into that.

And if one of us gets to it, I think we should also replace the background picture of index.html to adapt to the new look. What do you think should we do it in this PR or merge this now and have a look later? Other than that it looks good to me.

image

**Comment by meck93** [comment]
> Nice, thank you!
> 
> The index.html shows the serif font for me though, although it should be sans-serif even according to the computed CSS.. We should look into that.
> 
> And if one of us gets to it, I think we should also replace the background picture of index.html to adapt to the new look. What do you think should we do it in this PR or merge this now and have a look later? Other than that it looks good to me.
> 
> image

thanks for the review @felixmokross - I think I can probably fix it in this PR. Hopefully, in the next few days: 

- [ ] fix font
- [ ] replace background image

**Comment by meck93** [comment]
> Thanks for the review @felixmokross - I think I can probably fix it in this PR. Hopefully, in the next few days:
> 
> * [x]  fix font
> * [ ]  replace background image

Replacing the background image will be done as part of a follow-up story. See here: https://github.com/webplatformz/react-training-slides-v2/issues/22 @felixmokross did you have something specific in mind?

**Pull request merged**
