### PR TITLE
Feature/30 update zuehlke reveal package

### LINKED ISSUE #30: Update to new zuehlke-reveal-package version (new corporate design)
Demo can be found here: https://romanutti.github.io/zuehlke-reveal-demo

Blocked until the PR on zuehlke-reveal-package is merged: https://github.com/webplatformz/zuehlke-reveal-package/pull/2

### PR DESCRIPTION
**Pull request by felixmokross**
Migrate to latest release of [zuehlke-reveal-package](https://github.com/Zuehlke/zuehlke-reveal-package)
- Link to new package version in CSS <link> in the head, and in the <script> at the bottom of each file
- Used `title-slide` for chapter heading slides and `break-slide` for Questions slides
- Replaced `warn` class with `hl` (same effect, but `hl` is appropriately named and is the one mentioned in the zuehlke-reveal-package docs)
- Minor adaptions in code (but many changes due to Prettier reformatting)
- Added recommendation to install Prettier VS Code extension to README and set formatOnSave to true in workspace (to ensure files are always formatted consistently)

Closes #30 

image
image

### CODE REVIEW

**Comment by felixmokross** [comment]
We could also use some more features of the zuehlke-reveal-package, e.g. the Exercise slide or the Statement slide, to make the look-and-feel more interesting: https://github.com/Zuehlke/zuehlke-reveal-package/blob/main/doc/DOCUMENTATION.md But I would keep this for future PRs

**Comment by felixmokross** [comment]
I now made use of the agenda (for TOC) and subtitle-slide classes and added internal links to the TOC

image
image

**Comment by csalv22** [comment]
I don't know if this is common to repeat our names on every new chapter. We could make it less prominent?
image

I totally agree with the prettier settings and format&save - personally not my flavor of wrapping, but that doesn't matter at all, uniform code formatting inside a project is king :) 
image

**Review by csalv22 — APPROVED** [review]

**Comment by felixmokross** [comment]
> I don't know if this is common to repeat our names on every new chapter. We could make it less prominent?

I followed here how it is used in the CSS course: https://webplatformz.github.io/css-course/chapters/00-intro.html#/ In the demo slide they also suggest putting the "author": https://zuehlke.github.io/zuehlke-reveal-package/#/title-slide at this position. I anyway did it a bit differently though, because I think the chapter heading should be the most prominent in the visual hierarchy (and not the course name as it was done in the CSS course).

> I totally agree with the prettier settings and format&save - personally not my flavor of wrapping, but that doesn't matter at all, uniform code formatting inside a project is king :)

Yeah, I noticed that the prettier formatting is sometimes a bit strange in HTML. But at least consistent :D

**Pull request merged**
